### ISSUE TITLE
Error downloading boards

### ISSUE THREAD

**Issue by kritch83** [sparkfun/Arduino_Boards#85]
I am getting the following error trying to install the Sparkfun SAMD Boards 1.8.3.  It can't locate the file referenced in the boards file.  I am going by the Sparkfun install boards manager page and have done this a hundred times... I am getting this error on the two computers I tested it on and when trying to downgrade the library thats already installed.  Cant find file...

>  Error downloading https://github.com/sparkfun/Arduino_Boards/raw/master/IDE_Board_Manager/sparkfun-samd-1.8.3.tar.bz2
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/sparkfun/Arduino_Boards/raw/master/IDE_Board_Manager/sparkfun-samd-1.8.3.tar.bz2
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:179)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://github.com/sparkfun/Arduino_Boards/raw/master/IDE_Board_Manager/sparkfun-samd-1.8.3.tar.bz2
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:149)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:83)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:104)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 404
	at cc.arduino.utils.network.FileDownloader.openConnectionAndFillTheFile(FileDownloader.java:239)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:182)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:147)
	... 5 more

**Comment by nseidle** [comment]
Thanks for reporting @kritch83. I think we fixed it with [this PR](https://github.com/sparkfun/Arduino_Boards/pull/84). I'm able to install SAMD boards now. Please try again and let us know if it's still an issue.
